export const cacheKeys = {
  MY_ACCOUNT: "MY_ACCOUNT",
  ALL_COURSES: "ALL_COURSES",
  COURSE_DETAIL: "COURSE_DETAIL",
  COURSE_CONTENT_MINIMAL: "COURSE_CONTENT_MINIMAL",
  COURSE_REVIEW: "COURSE_REVIEW",
  COURSE_COMMENT: "COURSE_COMMENT",
  COMMENT_REPLIES: "COMMENT_REPLIES",
  GET_ENROLLMENT: "GET_ENROLLMENT",
};
