name: Deploy Next.js App (Production)

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.repository == 'Sourcepride/stacktrails'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm build

      - name: Create build archive
        run: tar -czf next-build.tar.gz .next

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "next-build.tar.gz"
          target: "/home/${{ secrets.SERVER_USER }}/stacktrails"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/stacktrails

            echo "ðŸ”„ Syncing with repository..."
            git fetch origin main
            git merge --ff-only origin/main || git reset --hard origin/main

            echo "ðŸ“¦ Installing dependencies..."
            pnpm install --frozen-lockfile

            echo "ðŸ—‘ï¸  Removing old build..."
            rm -rf .next

            echo "ðŸ“‚ Extracting new build..."
            tar -xzf next-build.tar.gz
            rm next-build.tar.gz

            echo "ðŸ” Creating environment file..."
            cat > .env.production << 'EOF'
            NODE_ENV=production
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_IMAGE_OPTS_TIMEOUT=${{ secrets.NEXT_IMAGE_OPTS_TIMEOUT }}
            NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            EOF

            echo "â™»ï¸  Restarting PM2..."
            pm2 reload stacktrails || pm2 start pnpm --name stacktrails -- start
            pm2 save

            echo "âœ… Deployment complete!"
