import ChatHeader from "@/components/chats/fragments/ChatHeader";
import ChatInputBox from "@/components/chats/fragments/input/ChatInputBox";
import Message from "@/components/chats/fragments/message/Message";

type ChatMainProps = {};

// Dummy chat data
const dummyChat: ChatRead = {
  id: "chat-1",
  chat_type: "GROUP",
  name: "React Developers Group",
  description: "Discussion about React best practices",
  avatar_url: undefined,
  privacy: "PUBLIC",
  is_active: true,
  last_message_at: new Date().toISOString(),
  account_id: "user1",
  course_id: undefined,
  account: {
    id: "user1",
    username: "admin",
    email: "admin@example.com",
    is_active: true,
    profile: {
      id: "profile1",
      account_id: "user1",
      display_name: "Admin User",
      avatar: undefined,
    },
  },
};

// Dummy members (5 members)
const dummyMembers: ChatMemberRead[] = [
  {
    id: "member-1",
    chat_id: "chat-1",
    account_id: "user1",
    role: "ADMIN",
    status: "ACTIVE",
    joined_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    left_at: undefined,
    notifications_enabled: true,
    is_pinned: false,
    last_read_message_id: undefined,
    is_admin: true,
    is_creator: true,
    account: {
      id: "user1",
      username: "johndoe",
      email: "john@example.com",
      is_active: true,
      profile: {
        id: "profile1",
        account_id: "user1",
        display_name: "John Doe",
        bio: "Software developer",
        avatar: undefined,
      },
    },
  },
  {
    id: "member-2",
    chat_id: "chat-1",
    account_id: "user2",
    role: "MEMBER",
    status: "ACTIVE",
    joined_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    left_at: undefined,
    notifications_enabled: true,
    is_pinned: false,
    last_read_message_id: undefined,
    is_admin: false,
    is_creator: false,
    account: {
      id: "user2",
      username: "sarahsmith",
      email: "sarah@example.com",
      is_active: true,
      profile: {
        id: "profile2",
        account_id: "user2",
        display_name: "Sarah Smith",
        avatar: undefined,
      },
    },
  },
  {
    id: "member-3",
    chat_id: "chat-1",
    account_id: "user3",
    role: "MEMBER",
    status: "ACTIVE",
    joined_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    left_at: undefined,
    notifications_enabled: true,
    is_pinned: false,
    last_read_message_id: undefined,
    is_admin: false,
    is_creator: false,
    account: {
      id: "user3",
      username: "mikejones",
      email: "mike@example.com",
      is_active: true,
      profile: {
        id: "profile3",
        account_id: "user3",
        display_name: "Mike Jones",
        avatar: undefined,
      },
    },
  },
  {
    id: "member-4",
    chat_id: "chat-1",
    account_id: "user4",
    role: "MEMBER",
    status: "ACTIVE",
    joined_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    left_at: undefined,
    notifications_enabled: true,
    is_pinned: false,
    last_read_message_id: undefined,
    is_admin: false,
    is_creator: false,
    account: {
      id: "user4",
      username: "emilychen",
      email: "emily@example.com",
      is_active: true,
      profile: {
        id: "profile4",
        account_id: "user4",
        display_name: "Emily Chen",
        avatar: undefined,
      },
    },
  },
  {
    id: "member-5",
    chat_id: "chat-1",
    account_id: "user5",
    role: "MEMBER",
    status: "ACTIVE",
    joined_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    left_at: undefined,
    notifications_enabled: true,
    is_pinned: false,
    last_read_message_id: undefined,
    is_admin: false,
    is_creator: false,
    account: {
      id: "user5",
      username: "alexbrown",
      email: "alex@example.com",
      is_active: true,
      profile: {
        id: "profile5",
        account_id: "user5",
        display_name: "Alex Brown",
        avatar: undefined,
      },
    },
  },
];

// Dummy messages (at least 10)
const dummyMessages: ChatMessageRead[] = [
  {
    id: "msg-1",
    chat_id: "chat-1",
    sender_id: "user1",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "Hey everyone! Welcome to the React Developers Group. Let's discuss best practices and share knowledge.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[0],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-2",
    chat_id: "chat-1",
    sender_id: "user2",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "Thanks for creating this group! I'm excited to learn more about React hooks and state management.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[1],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-3",
    chat_id: "chat-1",
    sender_id: "8c9b02d8-5796-4357-a6a7-883b5066eb7e",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "Great! Here's a useful resource: https://react.dev/learn\n\nCheck out the official React documentation for the latest patterns.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[0],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 100 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-4",
    chat_id: "chat-1",
    sender_id: "user3",
    reply_to_id: undefined,
    message_type: "IMAGE",
    content: "Here's a diagram I made showing the React component lifecycle",
    file_url:
      "https://via.placeholder.com/400x300?text=React+Lifecycle+Diagram",
    file_name: "react-lifecycle.png",
    file_size: 245760,
    file_type: "image/png",
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[2],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-5",
    chat_id: "chat-1",
    sender_id: "user4",
    reply_to_id: undefined,
    message_type: "TEXT",
    content: "That's really helpful! Thanks for sharing.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[3],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-6",
    chat_id: "chat-1",
    sender_id: "user1",
    reply_to_id: undefined,
    message_type: "FILE",
    content: "I've attached a comprehensive guide on React best practices",
    file_url: "https://example.com/react-best-practices.pdf",
    file_name: "react-best-practices.pdf",
    file_size: 1048576,
    file_type: "application/pdf",
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[0],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-7",
    chat_id: "chat-1",
    sender_id: "user5",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "Does anyone have experience with React Server Components? I'm trying to understand when to use them.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[4],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-8",
    chat_id: "chat-1",
    sender_id: "8c9b02d8-5796-4357-a6a7-883b5066eb7e",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "I've been using them in Next.js 13+. They're great for reducing client-side JavaScript bundle size. The key is understanding when data fetching happens on the server vs client.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: true,
    edited_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[1],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-9",
    chat_id: "chat-1",
    sender_id: "user1",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "Exactly! Server Components are perfect for:\n- Static content\n- Data fetching\n- Accessing backend resources\n- Keeping sensitive tokens off the client",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: {
      course_module: {
        id: "module-1",
        title: "React Server Components",
      },
    },
    chat: {
      ...dummyChat,
      course: {
        id: "course-1",
        slug: "react-advanced",
        title: "Advanced React Patterns",
        image: undefined,
        description: "Learn advanced React patterns",
        short_description: "Advanced React",
        learning_objectives: [],
        prerequisites: [],
        difficulty_level: "intermediate",
        estimated_duration_hours: 10,
        language: "en",
        status: "published",
        enrollment_type: "free",
        visibility: "public",
        certification_enabled: false,
        account_id: "user1",
        author: {
          email: "john@example.com",
          username: "johndoe",
          is_active: true,
          id: "user1",
        },
      },
    },
    sender: dummyMembers[0],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-10",
    chat_id: "chat-1",
    sender_id: undefined,
    reply_to_id: undefined,
    message_type: "SYSTEM",
    content: "Sarah Smith joined the group",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: null,
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-11",
    chat_id: "chat-1",
    sender_id: "8c9b02d8-5796-4357-a6a7-883b5066eb7e",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "Thanks for the explanation! This is really helpful. I'll check out the course module you referenced.",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[2],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-12",
    chat_id: "chat-1",
    sender_id: "user1",
    reply_to_id: undefined,
    message_type: "TEXT",
    content:
      "You're welcome! Feel free to ask any questions. We're all here to learn and help each other. 🚀",
    file_url: undefined,
    file_name: undefined,
    file_size: undefined,
    file_type: undefined,
    is_edited: false,
    edited_at: undefined,
    is_deleted: false,
    deleted_at: undefined,
    extra_data: null,
    chat: dummyChat,
    sender: dummyMembers[0],
    reply_to: undefined,
    reactions: [],
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export default function ChatMain(props: ChatMainProps) {
  return (
    <section className="bg-gray-100 flex flex-col justify-items-stretch items-stretch h-full relative ">
      <ChatHeader
        data={dummyChat}
        members={dummyMembers}
        onBack={() => {}}
        onSearch={() => {}}
        onDateFilter={() => {}}
      />
      <section className="relative grow overflow-y-auto px-4 py-4">
        <div className="flex flex-col">
          {dummyMessages.map((message) => (
            <Message key={message.id} message={message} />
          ))}
        </div>
      </section>
      <ChatInputBox />
    </section>
  );
}
